# -*- coding: utf-8 -*-
"""List_of_best_selling_PS4_games.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15d-tLUmUl5mHOcCsdHTVBYq56tt_iuRv

# **Import Libraries**
"""

import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import MinMaxScaler

"""# **Load DataSet**"""

df = pd.read_csv("/content/List of best-selling PlayStation 4 video games.csv")

print(df.head())

df.info()

df.shape

df.isnull().sum()

df.describe()

"""# **Data Preproccesing**"""

lst = []
for i in df['Copies sold']:
  lst.append(i.split()[0])
df['Copies sold'] = lst
df['Copies sold'] = pd.to_numeric(df["Copies sold"])
df["Release date[a]"] = pd.to_datetime(df["Release date[a]"])

"""## **Data Analysis**"""

barplot = px.bar(df, "Game", "Copies sold")
barplot.show()

df[df["Copies sold"] >= 15]

cercleplot = px.pie(df, "Genre(s)", "Copies sold")
cercleplot.show()